# will be shown in browser
pageTitle: "my pings"

listenPort: 9999
listenHost: 0.0.0.0

# global ping params
interval: 10s
size: 64
timeout: 1s

# this section can be skipped
basicAuth:
  - username: user
    password: password
  - username: admin
    password: 1

hosts:
  - name: google dns
    addr: 8.8.8.8

  - name: cloudflare dns
    addr: 1.1.1.1
    # some or all global params can be overriden
    interval: 5s 

  - name: offline host
    addr: 192.168.1.10
