ftikom: &FTIKOM 
  key: Provider
  markdown: true
  value: |
    phone: 123  
    address: hello



# will be shown in browser
pageTitle: "my pings"

listenPort: 9999
listenHost: 127.0.0.1

# global ping params
interval: 10s
size: 64
timeout: 6s
count: 5

# false: send information to frontend only if host status has changed, true: always send information
constant_updates: true

# this section can be skipped
basicAuth:
  - username: user
    password: password
  - username: admin
    password: 1

hosts:
  - name: google dns
    addr: 8.8.8.8
    info:
      - key: Organization
        value: Alphabet
      - key: telephone
        value: "**911**"
        markdown: true
      - <<: *FTIKOM

  - name: cloudflare dns
    addr: 1.1.1.1
    # some or all global params can be overriden
    interval: 15s 

  - name: offline host
    addr: 192.168.1.10


